#include "CppUTest/TestHarness.h"
#include "CppUTest/TestHarness_c.h"
//#include "CppUTestExt/MockSupport.h"


extern "C" {
#include <time.h> 
#include "EINT.h"
#include <avr/io.h>

	void do_nothing(uint8_t n);
};

void do_nothing(uint8_t n)
{

}

TEST_GROUP(TEST_EINT)
{
	void setup( )
	{
		memset(__avr_reg , 0 , _HIGHEST_REGISTER_ADD);
	}

	void teardown( )
	{

	}

};

#pragma region Enable_Tests

TEST(TEST_EINT , EINT_EnableCanBeCalled)
{
	EINT_enable(EINT_0);
}

TEST(TEST_EINT , EINT_0CanBeEnabled)
{
	EINT_enable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x01 , EIMSK);
}

TEST(TEST_EINT , EINT_1CanBeEnabled)
{
	EINT_enable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0x02 , EIMSK);
}

TEST(TEST_EINT , EINT_2CanBeEnabled)
{
	EINT_enable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x04 , EIMSK);
}

TEST(TEST_EINT , EINT_3CanBeEnabled)
{
	EINT_enable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x08 , EIMSK);
}

TEST(TEST_EINT , EINT_4CanBeEnabled)
{
	EINT_enable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x10 , EIMSK);
}

TEST(TEST_EINT , EINT_5CanBeEnabled)
{
	EINT_enable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0x20 , EIMSK);
}

TEST(TEST_EINT , EINT_6CanBeEnabled)
{
	EINT_enable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x40 , EIMSK);
}

TEST(TEST_EINT , EINT_7CanBeEnabled)
{
	EINT_enable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x80 , EIMSK);
}

TEST(TEST_EINT , EnableIsIndependent)
{
	EINT_enable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x10 , EIMSK);

	EINT_enable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x11 , EIMSK);

	EINT_enable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x19 , EIMSK);

	EINT_enable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x99 , EIMSK);
}

#pragma endregion

#pragma region Disable_Tests

TEST(TEST_EINT , EINT_DisableCanBeCalled)
{
	EINT_disable(EINT_0);
}

TEST(TEST_EINT , EINT_0CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0xFE , EIMSK);
}

TEST(TEST_EINT , EINT_1CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0xFD , EIMSK);
}

TEST(TEST_EINT , EINT_2CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0xFB , EIMSK);
}

TEST(TEST_EINT , EINT_3CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0xF7 , EIMSK);
}

TEST(TEST_EINT , EINT_4CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0xEF , EIMSK);
}

TEST(TEST_EINT , EINT_5CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0xDF , EIMSK);
}

TEST(TEST_EINT , EINT_6CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0xBF , EIMSK);
}

TEST(TEST_EINT , EINT_7CanBeDisabled)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x7F , EIMSK);
}

TEST(TEST_EINT , DisableIsIndependent)
{
	EIMSK = 0xFF;
	EINT_disable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0xEF , EIMSK);

	EINT_disable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0xE7 , EIMSK);

	EINT_disable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0xE5 , EIMSK);

	EINT_disable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0xC5 , EIMSK);
}

#pragma endregion

#pragma region EnableDisableTransition_Tests

TEST(TEST_EINT , EINT_0CanBeToggled)
{
	EINT_enable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x01 , EIMSK);

	EINT_disable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x01 , EIMSK);

	EINT_disable(EINT_0);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_1CanBeToggled)
{
	EINT_enable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0x02 , EIMSK);

	EINT_disable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0x02 , EIMSK);

	EINT_disable(EINT_1);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_2CanBeToggled)
{
	EINT_enable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x04 , EIMSK);

	EINT_disable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x04 , EIMSK);

	EINT_disable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_3CanBeToggled)
{
	EINT_enable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x08 , EIMSK);

	EINT_disable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x08 , EIMSK);

	EINT_disable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_4CanBeToggled)
{
	EINT_enable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x10 , EIMSK);

	EINT_disable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x10 , EIMSK);

	EINT_disable(EINT_4);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_5CanBeToggled)
{
	EINT_enable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0x20 , EIMSK);

	EINT_disable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0x20 , EIMSK);

	EINT_disable(EINT_5);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_6CanBeToggled)
{
	EINT_enable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x40 , EIMSK);

	EINT_disable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x40 , EIMSK);

	EINT_disable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , EINT_7CanBeToggled)
{
	EINT_enable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x80 , EIMSK);

	EINT_disable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);

	EINT_enable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x80 , EIMSK);

	EINT_disable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

TEST(TEST_EINT , ToggleIsIndependent)
{
	EINT_enable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x40 , EIMSK);

	EINT_enable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x48 , EIMSK);

	EINT_disable(EINT_6);
	CHECK_EQUAL_C_UBYTE(0x08 , EIMSK);

	EINT_enable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x88 , EIMSK);

	EINT_enable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x8C , EIMSK);

	EINT_disable(EINT_3);
	CHECK_EQUAL_C_UBYTE(0x84 , EIMSK);

	EINT_disable(EINT_2);
	CHECK_EQUAL_C_UBYTE(0x80 , EIMSK);

	EINT_disable(EINT_7);
	CHECK_EQUAL_C_UBYTE(0x00 , EIMSK);
}

#pragma endregion

#pragma region Set_sense_Tests

TEST(TEST_EINT , Set_SenseCanBeCalled)
{
	EINT_set_sense(EINT_0 , ISC_ANY);
}

TEST(TEST_EINT , EINT0CanBeSetToLow)
{
	EINT_set_sense(EINT_0 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT0CanBeSetToAny)
{
	EINT_set_sense(EINT_0 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x01 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT0CanBeSetToFalling)
{
	EINT_set_sense(EINT_0 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x02 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT0CanBeSetToRising)
{
	EINT_set_sense(EINT_0 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x03 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT1CanBeSetToLow)
{
	EINT_set_sense(EINT_1 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT1CanBeSetToAny)
{
	EINT_set_sense(EINT_1 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x04 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT1CanBeSetToFalling)
{
	EINT_set_sense(EINT_1 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x08 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT1CanBeSetToRising)
{
	EINT_set_sense(EINT_1 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x0C , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT2CanBeSetToLow)
{
	EINT_set_sense(EINT_2 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT2CanBeSetToAny)
{
	EINT_set_sense(EINT_2 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x10 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT2CanBeSetToFalling)
{
	EINT_set_sense(EINT_2 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x20 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT2CanBeSetToRising)
{
	EINT_set_sense(EINT_2 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x30 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT3CanBeSetToLow)
{
	EINT_set_sense(EINT_3 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT3CanBeSetToAny)
{
	EINT_set_sense(EINT_3 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x40 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT3CanBeSetToFalling)
{
	EINT_set_sense(EINT_3 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x80 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT3CanBeSetToRising)
{
	EINT_set_sense(EINT_3 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0xC0 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT4CanBeSetToLow)
{
	EINT_set_sense(EINT_4 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT4CanBeSetToAny)
{
	EINT_set_sense(EINT_4 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x01 , EICRB);
}

TEST(TEST_EINT , EINT4CanBeSetToFalling)
{
	EINT_set_sense(EINT_4 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x02 , EICRB);
}

TEST(TEST_EINT , EINT4CanBeSetToRising)
{
	EINT_set_sense(EINT_4 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x03 , EICRB);
}

TEST(TEST_EINT , EINT5CanBeSetToLow)
{
	EINT_set_sense(EINT_5 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT5CanBeSetToAny)
{
	EINT_set_sense(EINT_5 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x04 , EICRB);
}

TEST(TEST_EINT , EINT5CanBeSetToFalling)
{
	EINT_set_sense(EINT_5 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x08 , EICRB);
}

TEST(TEST_EINT , EINT5CanBeSetToRising)
{
	EINT_set_sense(EINT_5 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x0C , EICRB);
}

TEST(TEST_EINT , EINT6CanBeSetToLow)
{
	EINT_set_sense(EINT_6 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT6CanBeSetToAny)
{
	EINT_set_sense(EINT_6 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x10 , EICRB);
}

TEST(TEST_EINT , EINT6CanBeSetToFalling)
{
	EINT_set_sense(EINT_6 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x20 , EICRB);
}

TEST(TEST_EINT , EINT6CanBeSetToRising)
{
	EINT_set_sense(EINT_6 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x30 , EICRB);
}

TEST(TEST_EINT , EINT7CanBeSetToLow)
{
	EINT_set_sense(EINT_7 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

TEST(TEST_EINT , EINT7CanBeSetToAny)
{
	EINT_set_sense(EINT_7 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x40 , EICRB);
}

TEST(TEST_EINT , EINT7CanBeSetToFalling)
{
	EINT_set_sense(EINT_7 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x80 , EICRB);
}

TEST(TEST_EINT , EINT7CanBeSetToRising)
{
	EINT_set_sense(EINT_7 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0xC0 , EICRB);
}

TEST(TEST_EINT , SetIsIndependent)
{
	EINT_set_sense(EINT_7 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0xC0 , EICRB);

	EINT_set_sense(EINT_0 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x01 , EICRA);
	CHECK_EQUAL_C_UBYTE(0xC0 , EICRB);

	EINT_set_sense(EINT_1 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x09 , EICRA);
	CHECK_EQUAL_C_UBYTE(0xC0 , EICRB);

	EINT_set_sense(EINT_4 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x09 , EICRA);
	CHECK_EQUAL_C_UBYTE(0xC3 , EICRB);
}

TEST(TEST_EINT , CanBeReset)
{
	EINT_set_sense(EINT_6 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x30 , EICRB);

	EINT_set_sense(EINT_6 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x10 , EICRB);

	EINT_set_sense(EINT_6 , ISC_FALLING);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x20 , EICRB);

	EINT_set_sense(EINT_0 , ISC_RISING);
	CHECK_EQUAL_C_UBYTE(0x03 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x20 , EICRB);

	EINT_set_sense(EINT_4 , ISC_ANY);
	CHECK_EQUAL_C_UBYTE(0x03 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x21 , EICRB);

	EINT_set_sense(EINT_0 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x21 , EICRB);

	EINT_set_sense(EINT_6 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x01 , EICRB);

	EINT_set_sense(EINT_4 , ISC_LOW);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRA);
	CHECK_EQUAL_C_UBYTE(0x00 , EICRB);
}

#pragma endregion

#pragma region Callback_Tests

TEST(TEST_EINT , Set_CallbackCabBeCalled)
{
	EINT_set_callback(do_nothing);
}

#pragma endregion

